In [3]:
import pandas as pd
df=pd.read_csv('/Users/Malavika/Downloads/Aiplane_BlueBook.csv.xls')
df.shape

(861, 22)

In [5]:
df.columns

Index(['Model', 'Company', 'Engine Type', 'HP or lbs thr ea engine',
       'Max speed Knots', 'Rcmnd cruise Knots', 'Stall Knots dirty',
       'Fuel gal/lbs', 'All eng service ceiling', 'Eng out service ceiling',
       'All eng rate of climb', 'Eng out rate of climb', 'Takeoff over 50ft',
       'Takeoff ground run', 'Landing over 50ft', 'Landing ground roll',
       'Gross weight lbs', 'Empty weight lbs', 'Length ft/in', 'Height ft/in',
       'Wing span ft/in', 'Range N.M.'],
      dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=861, step=1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Model                    861 non-null    object
 1   Company                  861 non-null    object
 2   Engine Type              834 non-null    object
 3   HP or lbs thr ea engine  834 non-null    object
 4   Max speed Knots          791 non-null    object
 5   Rcmnd cruise Knots       811 non-null    object
 6   Stall Knots dirty        735 non-null    object
 7   Fuel gal/lbs             807 non-null    float64
 8   All eng service ceiling  780 non-null    float64
 9   Eng out service ceiling  332 non-null    object
 10  All eng rate of climb    752 non-null    object
 11  Eng out rate of climb    358 non-null    object
 12  Takeoff over 50ft        712 non-null    float64
 13  Takeoff ground run       691 non-null    float64
 14  Landing over 50ft        712 non-null    float64
 15  Landing ground roll      660 non-null    float64
 16  Gross weight lbs         830 non-null    object
 17  Empty weight lbs         834 non-null    object
 18  Length ft/in             822 non-null    object
 19  Height ft/in             819 non-null    object
 20  Wing span ft/in          832 non-null    object
 21  Range N.M.               758 non-null    object
dtypes: float64(6), object(16)
memory usage: 148.1+ KB

In [8]:
df.head()

,Model,Company,Engine Type,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng service ceiling,Eng out service ceiling,...,Takeoff over 50ft,Takeoff ground run,Landing over 50ft,Landing ground roll,Gross weight lbs,Empty weight lbs,Length ft/in,Height ft/in,Wing span ft/in,Range N.M.
0,15 AC Sedan,Aeronca,Piston,145,104,91,46,36.0,13000.0,NaN,...,900.0,NaN,1300.0,NaN,2050,1180,25/3,10/3,37/5,370
1,11 CC Super Chief,Aeronca,Piston,85,89,83,44,15.0,12300.0,NaN,...,720.0,NaN,800.0,NaN,1350,820,20/7,8/9,36/1,190
2,7 CCM Champ,Aeronca,Piston,90,90,78,37,19.0,16000.0,NaN,...,475.0,NaN,850.0,NaN,1300,810,21/5,8/7,35/0,210
3,7 DC Champ,Aeronca,Piston,85,88,78,37,19.0,13000.0,NaN,...,500.0,NaN,850.0,NaN,1300,800,21/5,8/7,35/0,210
4,7 AC Champ,Aeronca,Piston,65,83,74,33,14.0,12500.0,NaN,...,632.0,NaN,885.0,NaN,1220,740,21/5,8/9,35/0,175

In [9]:
df.tail()

,Model,Company,Engine Type,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng service ceiling,Eng out service ceiling,...,Takeoff over 50ft,Takeoff ground run,Landing over 50ft,Landing ground roll,Gross weight lbs,Empty weight lbs,Length ft/in,Height ft/in,Wing span ft/in,Range N.M.
856,500 A,Twin Commander A/C,Piston,260,198,190,54,156.0,22500.0,7850,...,1210.0,970.0,1150.0,865.0,6250,4255,35/1,14/5,49/5,957
857,500,Twin Commander A/C,Piston,250,190,178,55,156.0,22500.0,7150,...,1250.0,1000.0,1350.0,950.0,6000,3850,35/1,14/5,49/0,957
858,520,Twin Commander A/C,Piston,260,183,171,52,150.0,24000.0,8500,...,1100.0,950.0,1050.0,900.0,5500,3800,35/5,14/5,44/1,1000
859,2180,Varga,Piston,180,130,116,45,33.0,22000.0,NaN,...,NaN,NaN,NaN,NaN,1817,1175,21/2,7/0,30/0,365
860,2150A Kachina,Varga,Piston,150,117,104,45,33.0,22000.0,NaN,...,NaN,NaN,NaN,NaN,1817,1125,21/2,7/0,30/0,380

In [10]:
df.isnull().sum()

Model                        0
Company                      0
Engine Type                 27
HP or lbs thr ea engine     27
Max speed Knots             70
Rcmnd cruise Knots          50
Stall Knots dirty          126
Fuel gal/lbs                54
All eng service ceiling     81
Eng out service ceiling    529
All eng rate of climb      109
Eng out rate of climb      503
Takeoff over 50ft          149
Takeoff ground run         170
Landing over 50ft          149
Landing ground roll        201
Gross weight lbs            31
Empty weight lbs            27
Length ft/in                39
Height ft/in                42
Wing span ft/in             29
Range N.M.                 103
dtype: int64